version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ecommerce-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ecommerce
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:80" # host:container
    environment:
      REACT_APP_API_URL: http://backend:5000
    depends_on:
      - backend

volumes:
  db-data:
