apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce
spec:
  replicas: 2
  selector: { matchLabels: { app: backend } }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: crimson02/nodeback:latest
        ports: [{ containerPort: 5000 }]
        env:
        - name: POSTGRESS_URI
          value: "postgres://postgres:POSTGRES_PASSWORD@postgres-0.postgres.ecommerce.svc.cluster.local:5432/devopsdb"
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "256Mi" }
        livenessProbe:
          httpGet: { path: /api, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet: { path: /api, port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ecommerce
spec:
  selector: { app: backend }
  ports: [{ port: 5000, targetPort: 5000 }]
